### ISSUE TITLE
vmprofshow and vmprof.read_profile() can't read a vmprof file

### ISSUE THREAD

**Issue by dcrosta** [vmprof/vmprof-python#28] opened 2015-08-07 21:31 UTC
I am trying to use vmprof to profile a WSGI application running through gunicorn. I have, at the bottom of my main module, this:

```python
import os
import vmprof
fp = open("/tmp/vmprof.out-%s" % os.getpid(), "w")
vmprof.enable(fp.fileno(), warn=False)

def disable_at_exit():
    vmprof.disable()
    fp.close()

import atexit
atexit.register(disable_at_exit)
```

The file that results from this -- https://www.dropbox.com/s/ch33nyh9a2zp9vv/vmprof.out.gz?dl=0 for example -- can't be read with `vmprofshow` or `vmprof.read_profile()`:

```bash
dcrosta@bid001.sjc:~ $ /usr/local/opt/pypy/bin/vmprofshow ./vmprof.out
Fatal: could not read vmprof profile file './vmprof.out':
```

```python
>>>> import vmprof
>>>> vmprof.read_profile("vmprof.out")
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "/usr/local/opt/pypy-2.6-linux_x86_64-portable/site-packages/vmprof/profiler.py", line 54, in read_profile
    virtual_only, include_extra_info, interp_name)
  File "/usr/local/opt/pypy-2.6-linux_x86_64-portable/site-packages/vmprof/addrspace.py", line 141, in filter_addr
    interp_name, extra_info, only_virtual)
  File "/usr/local/opt/pypy-2.6-linux_x86_64-portable/site-packages/vmprof/addrspace.py", line 109, in _next_profile
    assert jitting
AssertionError
>>>>
```

CC @fijal

**Comment by dcrosta** [comment] 2015-08-07 21:33
This is with `vmprof==0.1.4.2`.

**Comment by dcrosta** [comment] 2015-08-11 14:55
FWIW, I was able to get `vmprofshow` to work by commenting out the line with `assert jitting`. Not sure if that compromises the results, though.

**Comment by fijal** [comment] 2015-08-11 21:01
So it turns out this got fixed with a more recent pypy, I'm gonna close it and please reopen if you find the bug again.

**Closed by fijal** 2015-08-11 21:01 UTC

**Comment by dcrosta** [comment] 2015-08-11 21:37
Any idea when the more recent PyPy will be released? (Presumably 2.6.1?)

**Comment by fijal** [comment] 2015-08-11 21:40
as soon as feasible, we did have a major buildbot downtime and are still picking up pieces :)

**Comment by dcrosta** [comment] 2015-08-11 21:44
Eek. Hadn't heard that. Let me know if I can help (build slave?)

**Comment by fijal** [comment] 2015-08-11 21:45
I'll let you know tomorrow, thanks for the offer!

**Comment by K0Te** [comment] 2015-09-08 13:15
It is still reproducible with PyPy-2.6.1.
Do you need any additional information about this issue ? (stats file, which leads to the issue?)

**Comment by fijal** [comment] 2015-09-16 15:41
I skipped the profiles that are unreadable. I still kinda fail to understand why they happen in such large amount, so you should get a warning if it's over 5% (but  we should look and fix it). Try the newer version
