### ISSUE TITLE
can't profile tests under nose

### ISSUE THREAD

**Issue by dimaqq** [vmprof/vmprof-python#20] opened 2015-06-25 12:30 UTC
I tried following:

create `tests/run.py` like this:
```
import sys, nose
sys.argv = [__file__, "--with-xxx", "tests"]
nose.main()
```

This runs 700-odd tests and takes ~10s.

When I run it under `python -m vmprof --web ...`, I get:
* a nice plot of all nose internals
* only one occurrence of one test file as `<module>`
* no occurrences of code under test

**Comment by xando** [comment] 2015-06-25 12:40
This project uses py.test not nose tests. Are you're trying to run tests? I'm lost.

**Comment by dimaqq** [comment] 2015-06-25 12:45
Those are my own tests for my own project.

I wanted to profile my own test / my own project.

**Comment by fijal** [comment] 2015-06-25 17:41
hi dima, how big is your log file? I know it gets truncated sometimes. Ideally I would need an exact information how to reproduce it. Are you using PyPy or CPython?

**Comment by dimaqq** [comment] 2015-06-25 18:36
I can generate and share a binary output.prof tomorrow.
I'm using CPython 2.7.10 in virtualenv.

**Comment by dimaqq** [comment] 2015-06-26 09:40
Hi Maciej, here's the binary output for run `python -m vmprof -n -o nosetests-file.prof tests/run.py`:
https://dima.egnyte.com/dl/B4zzWw0fZ5/nosetests-file.prof_

**Comment by dimaqq** [comment] 2015-06-26 10:07
Another possibility came to mind.
I seem to recall that nose internally calls sys.exit() instead of simply returning.
Could it be that vmperf doesn't handle SystemExit exception correctly?

**Comment by fijal** [comment] 2015-06-29 09:08
your file is 72k, which likely means it's cut a bit. I kinda wonder *why* it stopped reporting, maybe nose does something stupid to the signal handler (like cleans all the signals?)

**Comment by fijal** [comment] 2015-06-29 09:23
We should probably try to detect this case one way or another.

**Comment by dimaqq** [comment] 2015-06-29 11:45
If it helps to trace down the possibility of realtime (?) signal getting disabled, here's strace output:
https://dima.egnyte.com/dl/ly2NrHfgjY/vmprof.trace_

**Comment by fijal** [comment] 2015-06-29 14:04
I have an example where this occurs (with pypy though, so let me investigate)

**Comment by fijal** [comment] 2015-06-30 10:48
it looks like we broke fork() support, can you try again?

**Comment by dimaqq** [comment] 2015-06-30 11:50
In a simple command-line usage, I used to get `vmprof output:` and odd % values.
Now I only get `Profiling timer expired`.

Clearly there's a change, but I can't decide if it's an improvement :)

**Comment by fijal** [comment] 2015-06-30 16:58
Doing stuff without running the tests is bound to run into trouble.... try now

**Comment by dimaqq** [comment] 2015-07-01 10:39
Cool, now I get a proper long listing, including my functions under test!
Thanks @fijal

**Comment by fijal** [comment] 2015-07-01 16:51
Cool, closing this one

**Closed by fijal** 2015-07-01 16:51 UTC
