### ISSUE TITLE
vmprofwhow failed with exception: fail!

### ISSUE THREAD

**Issue by ARostovsky** [vmprof/vmprof-python#50] opened 2016-01-21 10:59 UTC
Hi! I tryed to run simple case and got an exception on view part:

```
C:\Python\Python27> .\python.exe .\Lib\site-packages\tests\cpuburn.py
Running for 30 seconds ..

Actual run-time: 1063.99989128 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1067.00015068 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1060.9998703 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1058.00008774 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1038.00010681 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1043.99991035 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1062.99996376 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1044.00014877 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1053.99990082 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1039.99996185 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1036.00001335 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1054.99982834 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1028.00011635 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1054.00013924 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1058.00008774 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1046.00000381 / Requested run-time: 1000, 15 iterations. Total iterations: 1500000
Actual run-time: 1001.99985504 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1036.00001335 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1060.9998703 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1012.99977303 / Requested run-time: 1000, 12 iterations. Total iterations: 1200000
Actual run-time: 1056.9999218 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1023.00000191 / Requested run-time: 1000, 13 iterations. Total iterations: 1300000
Actual run-time: 1036.99994087 / Requested run-time: 1000, 13 iterations. Total iterations: 1300000
Actual run-time: 1020.99990845 / Requested run-time: 1000, 13 iterations. Total iterations: 1300000
Actual run-time: 1058.00008774 / Requested run-time: 1000, 13 iterations. Total iterations: 1300000
Actual run-time: 1014.00017738 / Requested run-time: 1000, 13 iterations. Total iterations: 1300000
Actual run-time: 1023.00000191 / Requested run-time: 1000, 13 iterations. Total iterations: 1300000
Actual run-time: 1018.99981499 / Requested run-time: 1000, 13 iterations. Total iterations: 1300000
Actual run-time: 1009.00006294 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000
Actual run-time: 1025.00009537 / Requested run-time: 1000, 14 iterations. Total iterations: 1400000

Profile written to vmprof_cpuburn.dat.
To view the profile, run: vmprofshow vmprof_cpuburn.dat
```

```
C:\Python\Python27> .\Scripts\vmprofshow.exe .\vmprof_cpuburn.dat
←[37m←[1m100.0%←[0m ←[34m←[22m←[0m ←[34m←[1m<module>←[0m  ←[37m←[1m100.0%←[0m  ←[37m←[22m.\Lib\site-packages\tests/←[0m←
[37m←[1mcpuburn.py←[0m:←[37m←[22m1←[0m
←[37m←[1m100.0%←[0m ←[34m←[22m..←[0m ←[34m←[1mtest←[0m  ←[37m←[1m100.0%←[0m  ←[37m←[22m.\Lib\site-packages\tests/←[0m←[3
7m←[1mcpuburn.py←[0m:←[37m←[22m35←[0m
←[37m←[1m  0.0%←[0m ←[34m←[22m....←[0m ←[34m←[1m__init__←[0m  ←[37m←[1m0.0%←[0m  ←[37m←[22m.\Lib\site-packages\tests/←[0
m←[37m←[1mcpuburn.py←[0m:←[37m←[22m10←[0m
←[37m←[1m  0.0%←[0m ←[34m←[22m......←[0m ←[34m←[1m_next_rand←[0m  ←[37m←[1m100.0%←[0m  ←[37m←[22m.\Lib\site-packages\tes
ts/←[0m←[37m←[1mcpuburn.py←[0m:←[37m←[22m14←[0m
←[37m←[1m100.0%←[0m ←[34m←[22m....←[0m ←[34m←[1mburn←[0m  ←[37m←[1m100.0%←[0m  ←[37m←[22m.\Lib\site-packages\tests/←[0m←
[37m←[1mcpuburn.py←[0m:←[37m←[22m26←[0m
←[37m←[1m 99.9%←[0m ←[34m←[22m......←[0m ←[34m←[1m_iterate←[0m  ←[37m←[1m100.0%←[0m  ←[37m←[22m.\Lib\site-packages\tests
/←[0m←[37m←[1mcpuburn.py←[0m:←[37m←[22m19←[0m
←[37m←[1m 60.2%←[0m ←[34m←[22m........←[0m ←[34m←[1m_next_rand←[0m  ←[37m←[1m60.3%←[0m  ←[37m←[22m.\Lib\site-packages\te
sts/←[0m←[37m←[1mcpuburn.py←[0m:←[37m←[22m14←[0m
Traceback (most recent call last):
  File "c:\python\python27\lib\runpy.py", line 162, in _run_module_as_main
    "__main__", fname, loader, pkg_name)
  File "c:\python\python27\lib\runpy.py", line 72, in _run_code
    exec code in run_globals
  File "C:\Python\Python27\Scripts\vmprofshow.exe\__main__.py", line 9, in <module>
  File "c:\python\python27\lib\site-packages\click\core.py", line 716, in __call__
    return self.main(*args, **kwargs)
  File "c:\python\python27\lib\site-packages\click\core.py", line 696, in main
    rv = self.invoke(ctx)
  File "c:\python\python27\lib\site-packages\click\core.py", line 889, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "c:\python\python27\lib\site-packages\click\core.py", line 534, in invoke
    return callback(*args, **kwargs)
  File "c:\python\python27\lib\site-packages\vmprof\show.py", line 113, in main
    pp.show(profile)
  File "c:\python\python27\lib\site-packages\vmprof\show.py", line 50, in show
    self._print_tree(tree)
  File "c:\python\python27\lib\site-packages\vmprof\show.py", line 102, in _print_tree
    self._walk_tree(None, tree, 0, print_node)
  File "c:\python\python27\lib\site-packages\vmprof\show.py", line 58, in _walk_tree
    self._walk_tree(node, c, level, callback)
  File "c:\python\python27\lib\site-packages\vmprof\show.py", line 53, in _walk_tree
    callback(parent, node, level)
  File "c:\python\python27\lib\site-packages\vmprof\show.py", line 95, in print_node
    raise Exception("fail!")
Exception: fail!
```

It looks like a bug.
OS is Windows 8.1, Python version is 2.7, vmprof version is 0.2.3.1.

**Comment by fijal** [comment] 2016-01-21 15:24
vmprofshow is not very well supported it seems :/ can you upload the output profile?

**Comment by ARostovsky** [comment] 2016-01-21 15:35
Unfortunately I can't attach zip archive here (getting error 422 Unprocessable Entity), so I've sent it to you via email.

**Comment by fijal** [comment] 2016-01-21 17:52
ok, I think found it. The problem is that we don't stop tracking things across fork, which in turn causes the buffer to be written from two different files. Let's fix it.

**Comment by fijal** [comment] 2016-01-21 18:58
Ok, I pushed a new version that seems to fix this bug (at least in my mind, it's a bit difficult to reproduce), can you try now?

**Comment by fijal** [comment] 2016-01-21 18:58
I'm closing this, reopen if it continue

**Closed by fijal** 2016-01-21 18:58 UTC
